// q6_test.cpp - THE C++ CUBE, HELD TO THE GDSCRIPT'S OWN NUMBERS.
//
// There is one Q6 on desktop (scripts/core/iching/q6_lattice.gd) and one on
// device (android_plugin/ixmnn/src/main/cpp/q6/q6.cpp). Nothing in a build
// would notice if they drifted apart, so tests/golden/q6_golden.json -- eight
// fixed cases, written out by tools/q6_golden.gd from the GDScript -- is the
// ruler both are measured against. tests/q6_core.gd reads the same file from
// the Godot side.
//
// This program replays each case's `ops` through ix64::q6::Q6 and compares
// every number: the whole 64-vector, argmax, tension, best_neighbour and the
// 32-float embedding.
//
// BUILD (any C++17 compiler; no MNN, no JNI, no Android):
//   clang++ -std=c++17 -O2 -I../../android_plugin/ixmnn/src/main/cpp \
//       q6_test.cpp ../../android_plugin/ixmnn/src/main/cpp/q6/q6.cpp -o q6_test
//   cl /std:c++17 /EHsc /I..\..\android_plugin\ixmnn\src\main\cpp \
//       q6_test.cpp ..\..\android_plugin\ixmnn\src\main\cpp\q6\q6.cpp
//
// RUN (the json path is argv[1], or ../golden/q6_golden.json beside it):
//   ./q6_test ../golden/q6_golden.json
//
// Prints one line per check that fails and "=== ALL PASS ===" when none do.
// Exit code is the number of failures, capped at 125.

#include "q6/q6.hpp"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <memory>
#include <sstream>
#include <utility>
#include <string>
#include <vector>

// --- the smallest JSON reader that can read our own golden file -------------
//
// Deliberately tiny: objects, arrays, strings without escapes, numbers, and
// the three literals. The golden file is generated by us, so it never carries
// anything stranger than that.

namespace mini {

struct Value;
using ValuePtr = std::shared_ptr<Value>;

struct Value {
    enum Kind { Null, Bool, Number, String, Array, Object } kind = Null;
    bool b = false;
    double num = 0.0;
    std::string str;
    std::vector<ValuePtr> arr;
    std::map<std::string, ValuePtr> obj;

    const Value& operator[](int i) const { return *arr.at(static_cast<size_t>(i)); }
    const Value& operator[](const char* k) const { return *obj.at(k); }
    size_t size() const { return kind == Array ? arr.size() : obj.size(); }
    bool has(const char* k) const { return obj.count(k) != 0; }
};

class Parser {
public:
    // BY VALUE, not by reference: the caller hands us ss.str(), which is a
    // temporary, and a reference member would dangle the moment the constructor
    // returned.
    explicit Parser(std::string text) : s_(std::move(text)) {}

    ValuePtr parse() {
        skip();
        ValuePtr v = value();
        return v;
    }

private:
    const std::string s_;
    size_t i_ = 0;

    void skip() {
        while (i_ < s_.size() && (s_[i_] == ' ' || s_[i_] == '\t' || s_[i_] == '\n' ||
                                  s_[i_] == '\r')) {
            ++i_;
        }
    }

    ValuePtr value() {
        skip();
        if (i_ >= s_.size()) return std::make_shared<Value>();
        const char c = s_[i_];
        if (c == '{') return object();
        if (c == '[') return array();
        if (c == '"') return string();
        if (c == 't' || c == 'f') return boolean();
        if (c == 'n') {
            i_ += 4;
            return std::make_shared<Value>();
        }
        return number();
    }

    ValuePtr object() {
        auto v = std::make_shared<Value>();
        v->kind = Value::Object;
        ++i_;  // {
        skip();
        if (i_ < s_.size() && s_[i_] == '}') {
            ++i_;
            return v;
        }
        while (i_ < s_.size()) {
            skip();
            ValuePtr key = string();
            skip();
            if (i_ < s_.size() && s_[i_] == ':') ++i_;
            v->obj[key->str] = value();
            skip();
            if (i_ < s_.size() && s_[i_] == ',') {
                ++i_;
                continue;
            }
            if (i_ < s_.size() && s_[i_] == '}') ++i_;
            break;
        }
        return v;
    }

    ValuePtr array() {
        auto v = std::make_shared<Value>();
        v->kind = Value::Array;
        ++i_;  // [
        skip();
        if (i_ < s_.size() && s_[i_] == ']') {
            ++i_;
            return v;
        }
        while (i_ < s_.size()) {
            v->arr.push_back(value());
            skip();
            if (i_ < s_.size() && s_[i_] == ',') {
                ++i_;
                continue;
            }
            if (i_ < s_.size() && s_[i_] == ']') ++i_;
            break;
        }
        return v;
    }

    ValuePtr string() {
        auto v = std::make_shared<Value>();
        v->kind = Value::String;
        ++i_;  // "
        while (i_ < s_.size() && s_[i_] != '"') {
            if (s_[i_] == '\\' && i_ + 1 < s_.size()) ++i_;
            v->str.push_back(s_[i_]);
            ++i_;
        }
        if (i_ < s_.size()) ++i_;
        return v;
    }

    ValuePtr boolean() {
        auto v = std::make_shared<Value>();
        v->kind = Value::Bool;
        v->b = (s_[i_] == 't');
        i_ += v->b ? 4 : 5;
        return v;
    }

    ValuePtr number() {
        auto v = std::make_shared<Value>();
        v->kind = Value::Number;
        size_t start = i_;
        while (i_ < s_.size() && (std::isdigit(static_cast<unsigned char>(s_[i_])) ||
                                  s_[i_] == '-' || s_[i_] == '+' || s_[i_] == '.' ||
                                  s_[i_] == 'e' || s_[i_] == 'E')) {
            ++i_;
        }
        v->num = std::strtod(s_.substr(start, i_ - start).c_str(), nullptr);
        return v;
    }
};

}  // namespace mini

// --- the checks -------------------------------------------------------------

namespace {

int gChecks = 0;
int gFails = 0;

void check(bool ok, const std::string& what) {
    ++gChecks;
    if (!ok) {
        ++gFails;
        std::printf("FAIL %s\n", what.c_str());
    }
}

void checkNear(double got, double want, double eps, const std::string& what) {
    ++gChecks;
    if (!(std::fabs(got - want) <= eps)) {
        ++gFails;
        std::printf("FAIL %s (got %.17g want %.17g)\n", what.c_str(), got, want);
    }
}

// The same six numbers Pacing and Q6Core.bias_of() make: lines 0..2 are the
// machine's (lower) trigram, 3..5 the human's, each scaled by its own margin.
void biasOf(int targetBits, double machineMargin, double humanMargin, double* out) {
    const double m = machineMargin < 0.0 ? 0.0 : (machineMargin > 1.0 ? 1.0 : machineMargin);
    const double h = humanMargin < 0.0 ? 0.0 : (humanMargin > 1.0 ? 1.0 : humanMargin);
    for (int i = 0; i < ix64::q6::kLines; ++i) {
        const double sign = ((targetBits >> i) & 1) == 1 ? 1.0 : -1.0;
        out[i] = sign * (i < 3 ? m : h);
    }
}

}  // namespace

int main(int argc, char** argv) {
    std::string path = (argc > 1) ? argv[1] : "../golden/q6_golden.json";
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::printf("FAIL could not open golden file: %s\n", path.c_str());
        return 125;
    }
    std::ostringstream ss;
    ss << in.rdbuf();
    mini::Parser parser(ss.str());
    mini::ValuePtr doc = parser.parse();

    check(static_cast<int>((*doc)["states"].num) == ix64::q6::kStates,
          "the golden file and the C++ agree there are 64 corners");
    check(static_cast<int>((*doc)["lines"].num) == ix64::q6::kLines,
          "and six lines");
    check(static_cast<int>((*doc)["embed_dim"].num) == ix64::q6::kEmbedDim,
          "and a 32-float embedding");

    const mini::Value& cases = (*doc)["cases"];
    check(cases.size() > 0, "the golden file carries at least one case");

    for (size_t ci = 0; ci < cases.size(); ++ci) {
        const mini::Value& c = cases[static_cast<int>(ci)];
        const std::string name = c["name"].str;
        ix64::q6::Q6 q;

        const mini::Value& ops = c["ops"];
        for (size_t oi = 0; oi < ops.size(); ++oi) {
            const mini::Value& op = ops[static_cast<int>(oi)];
            const std::string what = op[0].str;
            if (what == "reset") {
                q.reset(static_cast<int>(op[1].num));
            } else if (what == "inject") {
                q.inject(static_cast<int>(op[1].num));
            } else if (what == "uniform") {
                q.uniform();
            } else if (what == "anchor") {
                q.anchor(static_cast<int>(op[1].num), op[2].num);
            } else if (what == "step") {
                double bias[ix64::q6::kLines];
                biasOf(static_cast<int>(op[1].num), op[2].num, op[3].num, bias);
                q.step(bias, op[4].num, op[5].num);
            } else {
                check(false, name + ": unknown op " + what);
            }
        }

        // THE WHOLE 64-VECTOR, corner by corner. A suite that only compared
        // argmax would pass on an implementation that got the shape wrong.
        const mini::Value& p = c["p"];
        double worst = 0.0;
        for (int h = 0; h < ix64::q6::kStates; ++h) {
            const double d = std::fabs(q.p[h] - p[h].num);
            if (d > worst) worst = d;
        }
        checkNear(worst, 0.0, 1e-12, name + ": every one of the 64 corners matches");

        checkNear(static_cast<double>(q.argmax()), c["argmax"].num, 0.0,
                  name + ": the corner holding the most mass");
        checkNear(q.tension(), c["tension"].num, 1e-12, name + ": tension");
        checkNear(static_cast<double>(q.bestNeighbour(static_cast<int>(c["from"].num))),
                  c["best_neighbour"].num, 0.0, name + ": the line that turns");

        // THE EMBEDDING is float32 on both sides, so it is compared at float32
        // resolution and no finer.
        float emb[ix64::q6::kEmbedDim];
        q.embed(emb);
        const mini::Value& want = c["embed"];
        double worstE = 0.0;
        for (int i = 0; i < ix64::q6::kEmbedDim; ++i) {
            const double d = std::fabs(static_cast<double>(emb[i]) -
                                       want[i].num);
            if (d > worstE) worstE = d;
        }
        checkNear(worstE, 0.0, 1e-6, name + ": all 32 Walsh coefficients match");
    }

    // THE PRIOR IS A RESCALING OF THE STATE, not a second opinion about it: a
    // uniform cube pushes all 64 figure words by exactly the same amount, so it
    // changes no ranking at all.
    {
        ix64::q6::Q6 q;
        q.uniform();
        const double first = ix64::q6::priorLogit(q, 0, 0.7);
        double spread = 0.0;
        for (int h = 0; h < ix64::q6::kStates; ++h) {
            spread = std::fmax(spread, std::fabs(ix64::q6::priorLogit(q, h, 0.7) - first));
        }
        checkNear(spread, 0.0, 1e-12,
                  "a cube with nothing to say moves every figure word equally");
        checkNear(first, 0.7, 1e-12, "and by weight / 64 * 64 = the weight itself");
        q.reset(42);
        checkNear(ix64::q6::priorLogit(q, 42, 0.7), 0.7 * 64.0, 1e-12,
                  "a cube standing on one corner pushes that word by weight * 64");
        checkNear(ix64::q6::priorLogit(q, 41, 0.7), 0.0, 1e-12, "and no other word at all");
        checkNear(ix64::q6::priorLogit(q, 42, 0.0), 0.0, 1e-12,
                  "and at weight zero it touches nothing");
        checkNear(ix64::q6::priorLogit(q, -1, 0.7), 0.0, 1e-12,
                  "a token that is not a figure word is left alone");
    }

    // The cube's own symmetries, checked without any reference numbers.
    for (int h = 0; h < ix64::q6::kStates; ++h) {
        check(ix64::q6::flip(ix64::q6::flip(h)) == h, "flip is its own inverse");
        check(ix64::q6::reverse(ix64::q6::reverse(h)) == h, "reverse is its own inverse");
        check(ix64::q6::popcount(h) + ix64::q6::popcount(ix64::q6::flip(h)) == 6,
              "a figure and its opposite have six yang lines between them");
    }

    std::printf("checks: %d\n", gChecks);
    if (gFails == 0) {
        std::printf("=== ALL PASS ===\n");
        return 0;
    }
    std::printf("=== %d FAILED ===\n", gFails);
    return gFails > 125 ? 125 : gFails;
}
