extends SceneTree
## THE SCHEMA, CARRIED OUT TO THE WEB STUDIO.
##
## tools/visualizer/index.html is a single static file a person opens off disk;
## it has no Godot in it and no way to ask the app what a tunable is. So the
## app writes the answer down. This script boots headless, asks
## [method HexyConfig.schema] for every row exactly as the dashboard does, and
## drops it beside the studio as config_schema.json.
##
## THE SCHEMA IS STILL THE TRUTH -- this file only copies it. Add a key to
## scripts/core/config.gd, run:
##
##   godot --headless --path . -s tools/gen_config_schema.gd
##
## and the studio grows the same row the phone grew. tests/test_config_schema_json.gd
## is what notices when nobody ran it.

const OUT_PATH: String = "res://tools/visualizer/config_schema.json"


func _initialize() -> void:
	var cfg := HexyConfig.new()
	cfg.autosave = false
	var doc: Dictionary = {
		"note": "generated by tools/gen_config_schema.gd from scripts/core/config.gd",
		"groups": cfg.groups(),
		"defaults": _defaults(cfg),
		"rows": cfg.schema(),
	}
	var f := FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if f == null:
		push_error("gen_config_schema: cannot write %s" % OUT_PATH)
		quit(1)
		return
	f.store_string(JSON.stringify(doc, "\t", true) + "\n")
	f.close()
	print("wrote ", OUT_PATH, " with ", cfg.keys().size(), " keys")
	HexyConfig.forget()
	quit(0)


## The drawer as a fresh build holds it: key -> default. This is the exact
## shape [method HexyConfig.to_json] writes, so the studio's export and the
## dashboard's paste are the same document.
func _defaults(cfg: HexyConfig) -> Dictionary:
	var out: Dictionary = {}
	for row in cfg.schema():
		out[String(row["key"])] = row["default"]
	return out
