extends SceneTree
## THE GOLDEN VECTORS, WRITTEN FROM THE GDSCRIPT.
##
## There is one Q6 on desktop (scripts/core/iching/q6_lattice.gd, reached
## through Q6Core) and one on device (android_plugin/ixmnn/src/main/cpp/q6),
## and nothing in a build would notice if they drifted apart. This file is the
## ruler both are measured against: it runs eight fixed cases through the
## GDScript and writes every number it saw into tests/golden/q6_golden.json.
##
##   tests/q6_core.gd      checks the GDScript client against the file.
##   tests/native/q6_test.cpp  checks the C++ against the SAME file.
##
## Run it only when the arithmetic is meant to change:
##   godot --headless --path . -s tools/q6_golden.gd
## Then run both suites. If the C++ goes red, the C++ is wrong.

const OUT_PATH: String = "res://tests/golden/q6_golden.json"

## Every number is written to this many places, which is more than a float64
## round-trip needs and far more than the 1e-9 the suites compare at.
const PLACES: int = 17


func _initialize() -> void:
	var cases: Array = []
	for c in _cases():
		cases.append(_run(c))
	var doc: Dictionary = {
		"note": "generated by tools/q6_golden.gd from scripts/core/iching/q6_lattice.gd",
		"lines": Q6Core.LINES,
		"states": Q6Core.STATES,
		"embed_dim": Q6Core.EMBED_DIM,
		"cases": cases,
	}
	var dir: String = OUT_PATH.get_base_dir()
	if not DirAccess.dir_exists_absolute(dir):
		DirAccess.make_dir_recursive_absolute(dir)
	var f: FileAccess = FileAccess.open(OUT_PATH, FileAccess.WRITE)
	if f == null:
		printerr("could not write ", OUT_PATH)
		quit(1)
		return
	f.store_string(JSON.stringify(doc, "  "))
	f.close()
	print("wrote ", cases.size(), " cases to ", OUT_PATH)
	quit(0)


## THE EIGHT CASES. Between them they touch every operation the native side
## has: reset, inject, uniform, anchor, one step at each fire's own diffusion
## time, a five-step walk that compounds float error, and one at a beta large
## enough that the whole distribution collapses into a few corners.
static func _cases() -> Array:
	return [
		{"name": "delta_zero", "from": 0, "ops": [["reset", 0]]},
		{"name": "delta_42", "from": 42, "ops": [["inject", 42]]},
		{"name": "uniform", "from": 0, "ops": [["uniform"]]},
		{
			"name": "anchored",
			"from": 7,
			"ops": [["reset", 42], ["anchor", 7, 0.5]],
		},
		{
			"name": "civil_step",
			"from": 42,
			"ops": [["reset", 42], ["anchor", 42, 0.5], ["step", 56, 1.0, 1.0, 0.06, 2.5]],
		},
		{
			"name": "martial_step",
			"from": 0,
			"ops": [["reset", 0], ["anchor", 0, 0.5], ["step", 21, 0.5, 0.25, 0.9, 2.5]],
		},
		{
			"name": "big_beta",
			"from": 0,
			"ops": [["reset", 0], ["anchor", 0, 0.5], ["step", 42, 1.0, 1.0, 0.06, 40.0]],
		},
		{
			"name": "five_step_walk",
			"from": 0,
			"ops": [
				["reset", 0],
				["anchor", 0, 0.5], ["step", 63, 1.0, 1.0, 0.06, 2.5],
				["anchor", 0, 0.5], ["step", 63, 1.0, 1.0, 0.06, 2.5],
				["anchor", 1, 0.5], ["step", 63, 1.0, 1.0, 0.06, 2.5],
				["anchor", 3, 0.5], ["step", 63, 0.8, 0.6, 0.9, 2.5],
				["anchor", 7, 0.5], ["step", 63, 1.0, 1.0, 0.06, 2.5],
			],
		},
	]


static func _run(c: Dictionary) -> Dictionary:
	# want_native false: the golden file is the GDScript's word, always.
	var cube: Q6Core = Q6Core.new(false)
	for op in (c["ops"] as Array):
		var a: Array = op as Array
		match String(a[0]):
			"reset":
				cube.reset(int(a[1]))
			"inject":
				cube.inject(int(a[1]))
			"uniform":
				cube.uniform()
			"anchor":
				cube.anchor(int(a[1]), float(a[2]))
			"step":
				var bias: PackedFloat64Array = Q6Core.bias_of(
					int(a[1]), float(a[2]), float(a[3]))
				cube.step(bias, float(a[4]), float(a[5]))
	var from_bits: int = int(c["from"])
	return {
		"name": String(c["name"]),
		"from": from_bits,
		"ops": c["ops"],
		"p": _round_all(cube.state()),
		"argmax": cube.argmax(),
		"tension": _round(cube.tension()),
		"best_neighbour": cube.best_neighbour(from_bits),
		"embed": _round_all_f32(cube.embed()),
	}


static func _round(x: float) -> float:
	return float(String.num(x, PLACES))


static func _round_all(v: PackedFloat64Array) -> Array:
	var out: Array = []
	for x in v:
		out.append(_round(x))
	return out


static func _round_all_f32(v: PackedFloat32Array) -> Array:
	var out: Array = []
	for x in v:
		out.append(_round(float(x)))
	return out
